//
//  RunMeButton.h
//  RunMe!
//
//  Created by Riccardo Rizzo on 11/07/16.
//  Copyright (c) 2016 Riccardo Rizzo. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface RunMeButton : NSObject

// Drawing Methods
+ (void)drawBlueButton:(CGRect)rect;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
